### PR TITLE
This solves an issue with the jquery-plugin that is important

### PR DESCRIPTION
**Pull request by calderonroberto**
I'm now using cookies to store some data to prevent thing leaks.

MIKE: it seems like my git clone is from develop and can't push to master. For future changes I rather have to go through this pull request than to push broken code.

I'll pull this myself.

### CODE REVIEW

**Comment by mblackstock** [comment]
You need to commit develop to develop, switch to master, merge with
develop, then push master. You can't push develop to master since the are
different branches.

**Comment by calderonroberto** [comment]
Yah I know. But my pull doesn't have the master branch.

**Comment by mblackstock** [comment]
OK. Next time you can switch to the master, then pull, then merge. That
should work.

**Comment by calderonroberto** [comment]
yup. Thanks.

**Pull request merged**
